version: "3"
services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    restart: always
    environment:
      - testEnvFromDocker=${AWS_ACCESS_KEY_ID}
    ports:
      - "4000:9070"
  