name: 'Auto Author Assign'

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: augustohp/github-action-pr-assignee
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"