name: Notify Slack on Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  slack-notification:
    runs-on: ubuntu-latest
    steps:
        - uses: 8398a7/action-slack@v3
          with:
            status: ${{ job.status }}
            fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
          env:
            SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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 # required
          if: always() # Pick up events even if the job fails or is canceled.
