name: Notify Slack on Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
                "text": "PR: ${{ github.event.pull_request.title}} by ${{ github.event.pull_request.user.login}}",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "PR_link: ${{ github.event.pull_request.html_url || github.event.head_commit.url }} by ${{ github.event.pull_request.user.login}}"
                    }
                  }
                ]
              }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
